import type { LanguageCode } from "./config";

export type Translation = {
  country: string; language: string; publicationsNav: string; externalSite: string;
  newTab: string; knowledgeCenter: string; valueKnowledge: string; heroDescription: string;
  ideas: string; publications: string; explore: string; selectYear: string; year: string;
  publication: string; publicationsPlural: string; noPublications: string; openDocument: string;
  services: string; rights: string;
};

export const translations: Record<LanguageCode, Translation> = {
  es: { country:"País", language:"Idioma", publicationsNav:"Publicaciones", externalSite:"ABALT Ecuador", newTab:"abre en una pestaña nueva", knowledgeCenter:"Centro de conocimiento", valueKnowledge:"Conocimiento que genera valor", heroDescription:"Un espacio que reúne publicaciones, boletines, análisis y contenidos técnicos desarrollados por ABALT para acompañar decisiones empresariales informadas.", ideas:"Ideas y perspectivas", publications:"Publicaciones", explore:"Explore nuestros boletines, análisis y documentos técnicos.", selectYear:"Seleccionar año", year:"Año", publication:"publicación", publicationsPlural:"publicaciones", noPublications:"No hay publicaciones disponibles para este año.", openDocument:"Abrir", services:"Contabilidad · Auditoría · Impuestos · Consultoría", rights:"Todos los derechos reservados." },
  en: { country:"Country", language:"Language", publicationsNav:"Publications", externalSite:"ABALT Ecuador", newTab:"opens in a new tab", knowledgeCenter:"Knowledge center", valueKnowledge:"Knowledge that creates value", heroDescription:"A space bringing together publications, bulletins, analyses and technical content developed by ABALT to support informed business decisions.", ideas:"Ideas and perspectives", publications:"Publications", explore:"Explore our bulletins, analyses and technical documents.", selectYear:"Select year", year:"Year", publication:"publication", publicationsPlural:"publications", noPublications:"No publications are available for this year.", openDocument:"Open", services:"Accounting · Audit · Tax · Consulting", rights:"All rights reserved." },
  pt: { country:"País", language:"Idioma", publicationsNav:"Publicações", externalSite:"ABALT Equador", newTab:"abre em uma nova aba", knowledgeCenter:"Centro de conhecimento", valueKnowledge:"Conhecimento que gera valor", heroDescription:"Um espaço que reúne publicações, boletins, análises e conteúdos técnicos desenvolvidos pela ABALT para apoiar decisões empresariais informadas.", ideas:"Ideias e perspectivas", publications:"Publicações", explore:"Explore nossos boletins, análises e documentos técnicos.", selectYear:"Selecionar ano", year:"Ano", publication:"publicação", publicationsPlural:"publicações", noPublications:"Não há publicações disponíveis para este ano.", openDocument:"Abrir", services:"Contabilidade · Auditoria · Impostos · Consultoria", rights:"Todos os direitos reservados." },
  fr: { country:"Pays", language:"Langue", publicationsNav:"Publications", externalSite:"ABALT Équateur", newTab:"s’ouvre dans un nouvel onglet", knowledgeCenter:"Centre de connaissances", valueKnowledge:"Des connaissances qui créent de la valeur", heroDescription:"Un espace qui rassemble les publications, bulletins, analyses et contenus techniques développés par ABALT pour éclairer les décisions des entreprises.", ideas:"Idées et perspectives", publications:"Publications", explore:"Découvrez nos bulletins, analyses et documents techniques.", selectYear:"Sélectionner l’année", year:"Année", publication:"publication", publicationsPlural:"publications", noPublications:"Aucune publication n’est disponible pour cette année.", openDocument:"Ouvrir", services:"Comptabilité · Audit · Fiscalité · Conseil", rights:"Tous droits réservés." },
  de: { country:"Land", language:"Sprache", publicationsNav:"Publikationen", externalSite:"ABALT Ecuador", newTab:"öffnet in einem neuen Tab", knowledgeCenter:"Wissenszentrum", valueKnowledge:"Wissen, das Werte schafft", heroDescription:"Ein Ort für Publikationen, Mitteilungen, Analysen und Fachinhalte von ABALT, die fundierte unternehmerische Entscheidungen unterstützen.", ideas:"Ideen und Perspektiven", publications:"Publikationen", explore:"Entdecken Sie unsere Mitteilungen, Analysen und Fachdokumente.", selectYear:"Jahr auswählen", year:"Jahr", publication:"Publikation", publicationsPlural:"Publikationen", noPublications:"Für dieses Jahr sind keine Publikationen verfügbar.", openDocument:"Öffnen", services:"Buchhaltung · Wirtschaftsprüfung · Steuern · Beratung", rights:"Alle Rechte vorbehalten." },
  ar: { country:"البلد", language:"اللغة", publicationsNav:"المنشورات", externalSite:"ABALT الإكوادور", newTab:"يفتح في علامة تبويب جديدة", knowledgeCenter:"مركز المعرفة", valueKnowledge:"معرفة تصنع القيمة", heroDescription:"مساحة تجمع المنشورات والنشرات والتحليلات والمحتوى الفني الذي تطوره ABALT لدعم قرارات الأعمال المستنيرة.", ideas:"أفكار ورؤى", publications:"المنشورات", explore:"استكشف نشراتنا وتحليلاتنا ووثائقنا الفنية.", selectYear:"اختر السنة", year:"السنة", publication:"منشور", publicationsPlural:"منشورات", noPublications:"لا توجد منشورات متاحة لهذه السنة.", openDocument:"فتح", services:"المحاسبة · التدقيق · الضرائب · الاستشارات", rights:"جميع الحقوق محفوظة." },
  zh: { country:"国家", language:"语言", publicationsNav:"出版物", externalSite:"ABALT 厄瓜多尔", newTab:"在新标签页中打开", knowledgeCenter:"知识中心", valueKnowledge:"创造价值的知识", heroDescription:"汇集 ABALT 出版物、简报、分析和专业内容，为明智的商业决策提供支持。", ideas:"观点与洞察", publications:"出版物", explore:"浏览我们的简报、分析和专业文件。", selectYear:"选择年份", year:"年份", publication:"篇出版物", publicationsPlural:"篇出版物", noPublications:"该年份暂无出版物。", openDocument:"打开", services:"会计 · 审计 · 税务 · 咨询", rights:"版权所有。" },
  ja: { country:"国", language:"言語", publicationsNav:"刊行物", externalSite:"ABALT エクアドル", newTab:"新しいタブで開きます", knowledgeCenter:"ナレッジセンター", valueKnowledge:"価値を生み出す知識", heroDescription:"ABALTが作成した刊行物、ニュースレター、分析、専門コンテンツを集め、十分な情報に基づく経営判断を支援します。", ideas:"アイデアと洞察", publications:"刊行物", explore:"ニュースレター、分析、専門文書をご覧ください。", selectYear:"年を選択", year:"年", publication:"件の刊行物", publicationsPlural:"件の刊行物", noPublications:"この年の刊行物はありません。", openDocument:"開く", services:"会計 · 監査 · 税務 · コンサルティング", rights:"無断転載を禁じます。" },
  ko: { country:"국가", language:"언어", publicationsNav:"간행물", externalSite:"ABALT 에콰도르", newTab:"새 탭에서 열림", knowledgeCenter:"지식 센터", valueKnowledge:"가치를 창출하는 지식", heroDescription:"ABALT가 개발한 간행물, 뉴스레터, 분석 및 전문 콘텐츠를 한곳에 모아 정보에 기반한 비즈니스 의사결정을 지원합니다.", ideas:"아이디어와 인사이트", publications:"간행물", explore:"뉴스레터, 분석 및 전문 문서를 살펴보세요.", selectYear:"연도 선택", year:"연도", publication:"개 간행물", publicationsPlural:"개 간행물", noPublications:"이 연도에는 간행물이 없습니다.", openDocument:"열기", services:"회계 · 감사 · 세무 · 컨설팅", rights:"모든 권리 보유." },
};
