import type { LanguageCode } from "./config";

export type Translation = {
  country: string; language: string; externalSite: string;
  newTab: string; knowledgeCenter: string; valueKnowledge: string; heroDescription: string;
  services: string; rights: string;
};

export const translations: Record<LanguageCode, Translation> = {
  es: { country:"País", language:"Idioma", externalSite:"ABALT Ecuador", newTab:"abre en una pestaña nueva", knowledgeCenter:"Centro de conocimiento", valueKnowledge:"Conocimiento que genera valor", heroDescription:"Un espacio que reúne publicaciones, boletines, análisis y contenidos técnicos desarrollados por ABALT para acompañar decisiones empresariales informadas.", services:"Contabilidad · Auditoría · Impuestos · Consultoría", rights:"Todos los derechos reservados." },
  en: { country:"Country", language:"Language", externalSite:"ABALT Ecuador", newTab:"opens in a new tab", knowledgeCenter:"Knowledge center", valueKnowledge:"Knowledge that creates value", heroDescription:"A space bringing together publications, bulletins, analyses and technical content developed by ABALT to support informed business decisions.", services:"Accounting · Audit · Tax · Consulting", rights:"All rights reserved." },
  pt: { country:"País", language:"Idioma", externalSite:"ABALT Equador", newTab:"abre em uma nova aba", knowledgeCenter:"Centro de conhecimento", valueKnowledge:"Conhecimento que gera valor", heroDescription:"Um espaço que reúne publicações, boletins, análises e conteúdos técnicos desenvolvidos pela ABALT para apoiar decisões empresariais informadas.", services:"Contabilidade · Auditoria · Impostos · Consultoria", rights:"Todos os direitos reservados." },
  fr: { country:"Pays", language:"Langue", externalSite:"ABALT Équateur", newTab:"s’ouvre dans un nouvel onglet", knowledgeCenter:"Centre de connaissances", valueKnowledge:"Des connaissances qui créent de la valeur", heroDescription:"Un espace qui rassemble les publications, bulletins, analyses et contenus techniques développés par ABALT pour éclairer les décisions des entreprises.", services:"Comptabilité · Audit · Fiscalité · Conseil", rights:"Tous droits réservés." },
  de: { country:"Land", language:"Sprache", externalSite:"ABALT Ecuador", newTab:"öffnet in einem neuen Tab", knowledgeCenter:"Wissenszentrum", valueKnowledge:"Wissen, das Werte schafft", heroDescription:"Ein Ort für Publikationen, Mitteilungen, Analysen und Fachinhalte von ABALT, die fundierte unternehmerische Entscheidungen unterstützen.", services:"Buchhaltung · Wirtschaftsprüfung · Steuern · Beratung", rights:"Alle Rechte vorbehalten." },
  ar: { country:"البلد", language:"اللغة", externalSite:"ABALT الإكوادور", newTab:"يفتح في علامة تبويب جديدة", knowledgeCenter:"مركز المعرفة", valueKnowledge:"معرفة تصنع القيمة", heroDescription:"مساحة تجمع المنشورات والنشرات والتحليلات والمحتوى الفني الذي تطوره ABALT لدعم قرارات الأعمال المستنيرة.", services:"المحاسبة · التدقيق · الضرائب · الاستشارات", rights:"جميع الحقوق محفوظة." },
  zh: { country:"国家", language:"语言", externalSite:"ABALT 厄瓜多尔", newTab:"在新标签页中打开", knowledgeCenter:"知识中心", valueKnowledge:"创造价值的知识", heroDescription:"汇集 ABALT 出版物、简报、分析和专业内容，为明智的商业决策提供支持。", services:"会计 · 审计 · 税务 · 咨询", rights:"版权所有。" },
  ja: { country:"国", language:"言語", externalSite:"ABALT エクアドル", newTab:"新しいタブで開きます", knowledgeCenter:"ナレッジセンター", valueKnowledge:"価値を生み出す知識", heroDescription:"ABALTが作成した刊行物、ニュースレター、分析、専門コンテンツを集め、十分な情報に基づく経営判断を支援します。", services:"会計 · 監査 · 税務 · コンサルティング", rights:"無断転載を禁じます。" },
  ko: { country:"국가", language:"언어", externalSite:"ABALT 에콰도르", newTab:"새 탭에서 열림", knowledgeCenter:"지식 센터", valueKnowledge:"가치를 창출하는 지식", heroDescription:"ABALT가 개발한 간행물, 뉴스레터, 분석 및 전문 콘텐츠를 한곳에 모아 정보에 기반한 비즈니스 의사결정을 지원합니다.", services:"회계 · 감사 · 세무 · 컨설팅", rights:"모든 권리 보유." },
};
